# Generated by Django 2.0.9 on 2022-06-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceimg', models.ImageField(null=True, upload_to='images_uploaded')),
                ('UserVideo', models.FileField(null=True, upload_to='videos_uploaded')),
            ],
        ),
    ]
