# Generated by Django 2.0.9 on 2022-06-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userdoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDoc',
        ),
    ]
